stages:
  - "Build"

##
## Build
##
build:
  stage: "Build"
  image: microsoft/dotnet:latest
  script:
    - cd src/
    - dotnet build exp-bullseye.csproj
    - dotnet publish --no-restore -c Release --output ../publish exp-bullseye.csproj 
    - dotnet pack exp-bullseye.csproj --output ../publish
    - dotnet exp-bullseye.dll default
  artifacts:
    expire_in: 1 week
    paths:
      - publish/